POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
  "userId": 1,
  "blogId": 8
}

###
POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
  "userId": 1,
  "blogId": 9
}


###
GET http://localhost:3001/api/readinglists


###
PUT http://localhost:3001/api/readinglists/4 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiY0BkZWYuY29tIiwiaWQiOjEsImlhdCI6MTY5MjkzNTc2MX0.11AKaRfEeF4yqho8BwX9IAChv2ehhYDTgVoKtUc4J9o

{
  "isRead": true
} 