GET http://localhost:3001/api/users 

###
GET http://localhost:3001/api/users/1

###
GET http://localhost:3001/api/users/1?isRead=false

###
GET http://localhost:3001/api/users/1?isRead=true

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Zu",
  "username": "abc@def.com"
} 

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "Zu2",
  "username": "abc2@def.com"
} 

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "Error"
} 

### TODO: change username
PUT http://localhost:3001/api/users/4 HTTP/1.1
Content-Type: application/json

{
  "username": "NotError"
} 